// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Default code", Scope = "type", Target = "~T:WebAPI.Program")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Default code", Scope = "type", Target = "~T:WebAPI.Startup")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "Self-explanatory", Scope = "type", Target = "~T:WebAPI.Constants.ErrorCode")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Self-explanatory", Scope = "namespaceanddescendants", Target = "WebAPI.Model")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "Autogenerated code", Scope = "namespaceanddescendants", Target = "WebAPI.Migrations")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "Autogenerated code", Scope = "namespaceanddescendants", Target = "WebAPI.Migrations")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1118:Parameter should not span multiple lines", Justification = "Autogenerated code", Scope = "namespaceanddescendants", Target = "WebAPI.Migrations")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Autogenerated code", Scope = "namespaceanddescendants", Target = "WebAPI.Migrations")]
