# Infrastructure deployment deploys a environment in its initial state, if applicatons are already deployed,
# they will be overwritten.  However, no databases or keyvaults will be overwritten.
#
# CI/PR Pipeline that deploys an ARM template to create or update the resources needed by the other pipelines.
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: prod-infra-vg

extends:
  template: infrastructure.yaml
  parameters: 
    ENVIRONMENT: production